<a href="https://colab.research.google.com/github/villain31/python3/blob/master/SciKit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [0]:
data = np.random.randint(0,100,(10,2))

In [3]:
data

array([[27, 29],
       [49, 46],
       [ 0, 93],
       [47, 40],
       [67, 95],
       [94, 82],
       [71, 94],
       [33, 72],
       [22, 13],
       [53, 79]])

In [0]:
scaler_model = MinMaxScaler()

In [5]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [6]:
scaler_model.fit(data)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[0.28723404, 0.19512195],
       [0.5212766 , 0.40243902],
       [0.        , 0.97560976],
       [0.5       , 0.32926829],
       [0.71276596, 1.        ],
       [1.        , 0.84146341],
       [0.75531915, 0.98780488],
       [0.35106383, 0.7195122 ],
       [0.23404255, 0.        ],
       [0.56382979, 0.80487805]])

In [8]:
scaler_model.fit_transform(data)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.28723404, 0.19512195],
       [0.5212766 , 0.40243902],
       [0.        , 0.97560976],
       [0.5       , 0.32926829],
       [0.71276596, 1.        ],
       [1.        , 0.84146341],
       [0.75531915, 0.98780488],
       [0.35106383, 0.7195122 ],
       [0.23404255, 0.        ],
       [0.56382979, 0.80487805]])

In [0]:
import pandas as pd

In [0]:
data = np.random.randint(0,101,(50,4))

In [11]:
data

array([[ 13,  73,   8,  94],
       [ 48,  29,  77,  53],
       [ 77,   4,  56,  44],
       [  4,   6,  92,  52],
       [ 40,  27,  49,  45],
       [ 38,  63,  37,  42],
       [100,  15,  75,   3],
       [ 63, 100,  53,   4],
       [ 42,  52,  57,  53],
       [ 86,  58,  49,  52],
       [ 35,  92,  36,  79],
       [ 68,  68,  36,   0],
       [  2,  45,  92,  21],
       [ 30,  89,  58,  53],
       [  9,  52,  26,  14],
       [ 55,  58,  37,  48],
       [ 87,  10,  54,  56],
       [ 65,  27,  18,  42],
       [ 69,  51,  97,  32],
       [ 78,  66, 100,  41],
       [ 56,  67,  25,  57],
       [ 62,  45,  60,   3],
       [  7,  48,  14,  58],
       [ 35,  88,  48,  77],
       [ 28,  95,  12,  93],
       [ 22,  14,  77,  68],
       [ 28,  32,   7,  41],
       [ 82,  53,  11,  46],
       [ 72,  77,  16,  48],
       [ 94,  21,  28,  72],
       [ 67,  91,  20,  41],
       [ 22,  45,  87,   7],
       [ 59,  22,  41,  81],
       [ 76,  22,  64,  86],
       [ 56,  

In [0]:
df = pd.DataFrame(data=data, columns=['f1','f2','f3','lable'])

In [13]:
df

f1   f2   f3  lable
0    13   73    8     94
1    48   29   77     53
2    77    4   56     44
3     4    6   92     52
4    40   27   49     45
5    38   63   37     42
6   100   15   75      3
7    63  100   53      4
8    42   52   57     53
9    86   58   49     52
10   35   92   36     79
11   68   68   36      0
12    2   45   92     21
13   30   89   58     53
14    9   52   26     14
15   55   58   37     48
16   87   10   54     56
17   65   27   18     42
18   69   51   97     32
19   78   66  100     41
20   56   67   25     57
21   62   45   60      3
22    7   48   14     58
23   35   88   48     77
24   28   95   12     93
25   22   14   77     68
26   28   32    7     41
27   82   53   11     46
28   72   77   16     48
29   94   21   28     72
30   67   91   20     41
31   22   45   87      7
32   59   22   41     81
33   76   22   64     86
34   56    3   79     26
35   46   46   36     97
36   50   17    8     19
37   18   48   63     18
38   73   93   88     61
39   33   51   88     56
40   76   35   15     94
41   12   98  100     73
42   58    2   20     34
43   24   23   89     33
44   72   90   98     41
45   60   76   12     58
46   62   71   84     78
47   48   89   89     49
48   80   90   14     17
49   50   48   81     35

In [0]:
X = df[['f1','f2','f3']]
y = df['lable']

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [17]:
X_train.shape

(35, 3)

In [18]:
X_test.shape

(15, 3)